const BAD_REQUEST = 400;
const UNAUATHORIZED =401
const NOT_FOUND = 404;
const FORBIDDEN = 403
const DUPLICATE_ERROR = 409
const DEFAULT_ERROR = 500;
const MONGODB_ERROR = 11000

module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  DEFAULT_ERROR,
  MONGODB_ERROR,
  UNAUATHORIZED,
  FORBIDDEN,
  DUPLICATE_ERROR
};
